name: update_members

on:
  workflow_dispatch:
  schedule:
  - cron: "5 23 * * 5"

jobs:
  build:
    name: Create pages for new members
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run Script
        run: |
          cd scripts/; python generate_members.py
          cd ..

      - name: Deploy
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/_pessoas/
          git commit -m "chore: Atualiza página de membros"
          git push
